version: "3.8"
services:
  robotics:
    image: robotics:dev
    container_name: robotics-dev
    env_file: ./.env
    user: ${DOCKER_UID}:${DOCKER_GID}
    network_mode: ${NETWORK_MODE}
    stdin_open: true
    tty: true
    ipc: host
    privileged: true
    restart: always
    runtime: ${RUNTIME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    volumes:
      # x11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # datasets
      - ~/data/:/home/${DOCKER_USER}/data:ro
    build:
      context: .
      network: ${NETWORK_MODE}
      dockerfile: Dockerfile
      target: robotics
      args:
        DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
        OS: ${OS}
        ARCH: ${ARCH}
        BASE_IMAGE: ${BASE_IMAGE}
        UBUNTU_DISTRO: ${UBUNTU_DISTRO}
        COMPILE_JOBS: ${COMPILE_JOBS}
        DEPENDENCIES_DIR: ${DEPENDENCIES_DIR}
        ROS2_DISTRO: ${ROS2_DISTRO}
        ROS2_RELEASE_DATE: ${ROS2_RELEASE_DATE}
        RTI_CONNEXT_DDS_VERSION: ${RTI_CONNEXT_DDS_VERSION}
        OPENCV_VERSION: ${OPENCV_VERSION}
        OPENCV_CONTRIB_VERSION: ${OPENCV_CONTRIB_VERSION}
        CERES_VERSION: ${CERES_VERSION}
        NEOVIM_VERSION: ${NEOVIM_VERSION}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_GID: ${DOCKER_GID}
