version: "3.8"
services:
  robotics-dev:
    env_file: ./.env
    image: robotics-dev:latest
    container_name: robotics_dev
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        COMPILE_JOBS: ${COMPILE_JOBS}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        OS: ${OS}
        CMAKE_VERSION: ${CMAKE_VERSION}
        PYTHON3_VERSION: ${PYTHON3_VERSION}
        OPENCV3_VERSION: ${OPENCV3_VERSION}
        OPENCV4_VERSION: ${OPENCV4_VERSION}
        EIGEN_VERSION: ${EIGEN_VERSION}
        CERES_VERSION: ${CERES_VERSION}
        ROS_DISTRO: ${ROS_DISTRO}
        ROS_DISTRO_TAG: ${ROS_DISTRO_TAG}
        GAZEBO_DISTRO: ${GAZEBO_DISTRO}
        USER: ${USER}
        UID: ${UID}
        GID: ${GID}
        NEOVIM_VERSION: ${NEOVIM_VERSION}
        TMUX_VERSION: ${TMUX_VERSION}
        CARLA_VERSION: ${CARLA_VERSION}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - SDL_VIDEODRIVER=x11
    runtime: nvidia
    user: ${UID}:${GID}
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      # x11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # personal configurations
      - ~/.config/nvim/:${HOME}/.config/nvim/:ro
      - ~/.tmux.conf:${HOME}/.tmux.conf:ro
      - ~/.gitconfig:${HOME}/.gitconfig:ro
    restart: always
