services:
  robotics:
    build:
      args:
        ARCH: ${ARCH}
        BASE_IMAGE: ${BASE_IMAGE}
        BOOST_VERSION: ${BOOST_VERSION}
        BUILDTIME_NETWORK_MODE: ${BUILDTIME_NETWORK_MODE}
        CERES_VERSION: ${CERES_VERSION}
        CMAKE_VERSION: ${CMAKE_VERSION}
        COMPILE_JOBS: ${COMPILE_JOBS}
        DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
        DOCKER_GID: ${DOCKER_GID}
        DOCKER_HOME: ${DOCKER_HOME}
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_USER: ${DOCKER_USER}
        FLANN_VERSION: ${FLANN_VERSION}
        NEOVIM_VERSION: ${NEOVIM_VERSION}
        OPENCV_CONTRIB_VERSION: ${OPENCV_CONTRIB_VERSION}
        OPENCV_VERSION: ${OPENCV_VERSION}
        OS: ${OS}
        PCL_GIT_REFERENCE: ${PCL_GIT_REFERENCE}
        ROS2_DISTRO: ${ROS2_DISTRO}
        SETUP_TIMESTAMP: ${SETUP_TIMESTAMP}
        TMUX_GIT_REFERENCE: ${TMUX_GIT_REFERENCE}
        VTK_VERSION: ${VTK_VERSION}
        XDG_PREFIX_DIR: ${XDG_PREFIX_DIR}
      context: .
      dockerfile: Dockerfile
      network: ${BUILDTIME_NETWORK_MODE}
      target: ${BUILD_TARGET}
    command: zsh
    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        reservations:
          devices:
          - capabilities:
            - gpu
            count: all
            driver: nvidia
    env_file: ./.env
    extra_hosts:
    - host.docker.internal:host-gateway
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    ipc: host
    network_mode: ${RUNTIME_NETWORK_MODE}
    privileged: true
    restart: always
    runtime: ${RUNTIME}
    stdin_open: true
    tty: true
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
    - ~/Datasets:${DOCKER_HOME}/Datasets:rw
    - ~/Projects:${DOCKER_HOME}/Projects:rw
    - ~/Documents:${DOCKER_HOME}/Documents:rw
    - ~/.ssh:${DOCKER_HOME}/.ssh:ro
    - ~/.config/msmtp:${DOCKER_HOME}/.config/msmtp:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY:rw
    - /run/user/1000/bus:/run/user/1000/bus:rw
