version: "3.8"
services:
  robotics-dev:
    image: robotics-dev:latest
    container_name: robotics-dev
    env_file: ./.env
    user: ${DOCKER_UID}:${DOCKER_GID}
    network_mode: ${NETWORK_MODE}
    stdin_open: true
    tty: true
    ipc: host
    privileged: true
    restart: always
    runtime: ${RUNTIME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    volumes:
      # x11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # personal configurations
      - ~/.config/nvim/:/home/${DOCKER_USER}/.config/nvim/:ro
      - ~/.tmux.conf:/home/${DOCKER_USER}/.tmux.conf:ro
      - ~/.gitconfig:/home/${DOCKER_USER}/.gitconfig:ro
    build:
      context: .
      network: ${NETWORK_MODE}
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: ${DOCKER_BUILDKIT}
        OS: ${OS}
        ARCH: ${ARCH}
        UBUNTU_DISTRO: ${UBUNTU_DISTRO}
        UBUNTU_RELEASE_DATE: ${UBUNTU_RELEASE_DATE}
        COMPILE_JOBS: ${COMPILE_JOBS}
        ROS2_DISTRO: ${ROS2_DISTRO}
        ROS2_RELEASE_DATE: ${ROS2_RELEASE_DATE}
        PYTHON_VERSION: ${PYTHON_VERSION}
        CMAKE_VERSION: ${CMAKE_VERSION}
        OPENCV_VERSION: ${OPENCV_VERSION}
        EIGEN_VERSION: ${EIGEN_VERSION}
        CERES_VERSION: ${CERES_VERSION}
        GAZEBO_DISTRO: ${GAZEBO_DISTRO}
        CARLA_VERSION: ${CARLA_VERSION}
        NEOVIM_VERSION: ${NEOVIM_VERSION}
        TMUX_VERSION: ${TMUX_VERSION}
        NVM_VERSION: ${NVM_VERSION}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_GID: ${DOCKER_GID}
