#!/bin/bash
# A '.env' file will be generated by this script in the same parent directory, 
# containing the following environment variables. 
#
# These variables are utilized both during build time and runtime.
#
# If you wish to add or modify other environment variables, 
# make sure to synchronize changes across all three files: 
# 'Dockerfile', 'docker-compose.yml', and 'setup.bash'. 
#
set -e
echo "
http_proxy=http://127.0.0.1:1080
https_proxy=https://127.0.0.1:1080
HTTP_PROXY=http://127.0.0.1:1080
HTTPS_PROXY=https://127.0.0.1:1080
COMPILE_JOBS=8
OS=ubuntu:22.04
ROS_DISTRO=iron
ROS_DISTRO_TAG=desktop
CMAKE_VERSION=3.27.7
PYTHON3_VERSION=3.12.0
OPENCV3_VERSION=3.4.16
OPENCV4_VERSION=4.8.0
EIGEN_VERSION=3.4.0
CERES_VERSION=2.2.0
NEOVIM_VERSION=0.9.4
TMUX_VERSION=3.3a
USER=${USER}
UID=$(id -u)
GID=$(id -g)
DISPLAY=${DISPLAY}
" > $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/.env
